"""add chunk links and word count

Revision ID: 22c7a9a62523
Revises: 50b84197f9d2
Create Date: 2026-07-11 20:16:19.283249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22c7a9a62523'
down_revision: Union[str, Sequence[str], None] = '50b84197f9d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('word_count', sa.Integer(), nullable=True))
    op.add_column('chunks', sa.Column('prev_chunk_id', sa.UUID(as_uuid=False), nullable=True))
    op.add_column('chunks', sa.Column('next_chunk_id', sa.UUID(as_uuid=False), nullable=True))

    # Migrate old token counts into word_count.
    op.execute("UPDATE chunks SET word_count = token_count")

    op.drop_column('chunks', 'token_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('token_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('chunks', 'next_chunk_id')
    op.drop_column('chunks', 'prev_chunk_id')
    op.drop_column('chunks', 'word_count')
    # ### end Alembic commands ###
