"""add document file stat snapshot

Revision ID: 27b1f434b86b
Revises: 22c7a9a62523
Create Date: 2026-07-14 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27b1f434b86b'
down_revision: Union[str, Sequence[str], None] = '22c7a9a62523'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column(
        'documents',
        sa.Column('file_modified_at', sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file_modified_at')
    op.drop_column('documents', 'file_size')
    # ### end Alembic commands ###
