"""initial schema

Revision ID: 319a472d5583
Revises: 
Create Date: 2026-07-09 22:59:32.262768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '319a472d5583'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('document_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('cleaned_content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('embedding_model', sa.String(length=512), nullable=True),
    sa.Column('vector_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('fts_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chunks_document_id', 'chunks', ['document_id'], unique=False)
    op.create_index('ix_chunks_fts', 'chunks', ['fts_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_chunks_vector_id', 'chunks', ['vector_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('source_type', sa.Enum('LOCAL', 'S3', 'GCS', 'AZURE_BLOB', name='sourcetype'), nullable=False),
    sa.Column('source_uri', sa.String(length=2048), nullable=False),
    sa.Column('filename', sa.String(length=1024), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'INDEXING', 'PARSED', 'CHUNKED', 'EMBEDDED', 'COMPLETED', 'FAILED', 'DELETED', name='documentstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_deleted_at', 'documents', ['deleted_at'], unique=False)
    op.create_index('ix_documents_source_uri', 'documents', ['source_uri'], unique=True)
    op.create_index('ix_documents_status', 'documents', ['status'], unique=False)
    op.create_table('logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('component', sa.String(length=256), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('extra', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_logs_component', 'logs', ['component'], unique=False)
    op.create_index('ix_logs_created_at', 'logs', ['created_at'], unique=False)
    op.create_index('ix_logs_level', 'logs', ['level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_logs_level', table_name='logs')
    op.drop_index('ix_logs_created_at', table_name='logs')
    op.drop_index('ix_logs_component', table_name='logs')
    op.drop_table('logs')
    op.drop_index('ix_documents_status', table_name='documents')
    op.drop_index('ix_documents_source_uri', table_name='documents')
    op.drop_index('ix_documents_deleted_at', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_chunks_vector_id', table_name='chunks')
    op.drop_index('ix_chunks_fts', table_name='chunks', postgresql_using='gin')
    op.drop_index('ix_chunks_document_id', table_name='chunks')
    op.drop_table('chunks')
    # ### end Alembic commands ###
