"""add retrieval and chunk metadata fields

Revision ID: 50b84197f9d2
Revises: d715f71dd3f7
Create Date: 2026-07-11 02:29:00.053463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50b84197f9d2'
down_revision: Union[str, Sequence[str], None] = 'd715f71dd3f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('embedding_collections',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('embedding_provider', sa.String(length=128), nullable=False),
    sa.Column('embedding_model', sa.String(length=512), nullable=False),
    sa.Column('model_version', sa.String(length=256), nullable=True),
    sa.Column('vector_size', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('chunks', sa.Column('parent_chunk_index', sa.Integer(), nullable=True))
    op.add_column('chunks', sa.Column('section_title', sa.String(length=1024), nullable=True))
    op.add_column('chunks', sa.Column('page_number', sa.Integer(), nullable=True))
    op.add_column('chunks', sa.Column('start_offset', sa.Integer(), nullable=True))
    op.add_column('chunks', sa.Column('end_offset', sa.Integer(), nullable=True))
    op.add_column('chunks', sa.Column('content_hash', sa.String(length=128), nullable=True))
    op.create_index('ix_chunks_content_hash', 'chunks', ['content_hash'], unique=False)
    op.add_column('documents', sa.Column('tenant_id', sa.String(length=256), nullable=True))
    op.add_column('documents', sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True))
    op.create_index('ix_documents_tenant_id', 'documents', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_tenant_id', table_name='documents')
    op.drop_column('documents', 'tags')
    op.drop_column('documents', 'tenant_id')
    op.drop_index('ix_chunks_content_hash', table_name='chunks')
    op.drop_column('chunks', 'content_hash')
    op.drop_column('chunks', 'end_offset')
    op.drop_column('chunks', 'start_offset')
    op.drop_column('chunks', 'page_number')
    op.drop_column('chunks', 'section_title')
    op.drop_column('chunks', 'parent_chunk_index')
    op.drop_table('embedding_collections')
    # ### end Alembic commands ###
